version: '3'
services:
  mirror-update:
    build: update
    environment:
        - ARCHLINUX_T1_RSYNC_URL
 
    restart: always
    volumes:
      - mirror-data:/mnt/mirror

  mirror-http:
    build: 
      args:
        - URL_AUTHORITY
      context: http
    environment:
        - CERTBOT_AGREE_FLAG
        - CERTBOT_EMAIL
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - mirror-data:/mnt/mirror
      - ssl-letsencrypt:/etc/letsencrypt
      - ssl-certbot:/var/www/certbot

  certbot:
    image: certbot/certbot:v1.14.0
    restart: always 
    volumes:
      - ssl-letsencrypt:/etc/letsencrypt
      - ssl-certbot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  mirror-data:
  ssl-letsencrypt:
  ssl-certbot:

